name: Deployment Workflow
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: resume.phanminhhung.tech
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/learn-threejs
            eval `ssh-agent -s`
            ssh-add ~/.ssh/github
            git pull origin main
            git status
            export PATH=/home/${{ secrets.SSH_USERNAME }}/.nvm/versions/node/v20.12.2/bin:/usr/bin:/bin;
            yarn install
            rm -rf .next
            yarn build
            pm2 restart learn-threejs